"""Tests for the editor/agent shim writer (DEC-031).

The shim writer drops 10 targets into a target repo:
- 4 editor shims (CLAUDE.md, AGENTS.md, .cursor/rules/codebase.mdc,
  .continue/rules/codebase.md)
- 5 emitted skills (.claude/skills/codebase-{exploring,debugging,
  impact-analysis,refactoring,onboarding}/SKILL.md)
- 1 Claude Code plugin manifest (.claude-plugin/plugin.json)

All are write-if-absent — hand-edited files / skills are never overwritten.
"""

from __future__ import annotations

import json
from pathlib import Path

from forensic_deepdive.emit.shims import write_shims

# All 10 expected target relative paths.
_EDITOR_SHIMS = (
    "CLAUDE.md",
    "AGENTS.md",
    ".cursor/rules/codebase.mdc",
    ".continue/rules/codebase.md",
)
_SKILL_NAMES = (
    "codebase-exploring",
    "codebase-debugging",
    "codebase-impact-analysis",
    "codebase-refactoring",
    "codebase-onboarding",
)
_SKILL_PATHS = tuple(f".claude/skills/{n}/SKILL.md" for n in _SKILL_NAMES)
_PLUGIN_MANIFEST = ".claude-plugin/plugin.json"
_ALL_TARGETS = _EDITOR_SHIMS + _SKILL_PATHS + (_PLUGIN_MANIFEST,)


def test_write_shims_creates_all_ten(tmp_path: Path) -> None:
    """A fresh repo gets every editor shim, every skill, and the plugin manifest."""
    result = write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    assert len(result.written) == 10
    assert not result.skipped
    for rel in _ALL_TARGETS:
        assert (tmp_path / rel).is_file(), f"missing target: {rel}"
    # Brief path appears in every editor shim.
    for rel in _EDITOR_SHIMS:
        assert "docs/codebase/AGENT_BRIEF.md" in (tmp_path / rel).read_text(encoding="utf-8")


def test_editor_shim_lists_all_nine_mcp_tools(tmp_path: Path) -> None:
    """The generated CLAUDE.md/AGENTS.md must name all nine MCP tools the server
    actually exposes (was stale at five: missing record_insight/recall_insights/
    visualize/trace). An onboarded agent is told what's available."""
    write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    body = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    for tool in (
        "impact",
        "context",
        "archaeology",
        "flow",
        "query",
        "record_insight",
        "recall_insights",
        "visualize",
        "trace",
    ):
        assert f"`{tool}`" in body, f"shim omits MCP tool: {tool}"
    assert "five composite tools" not in body


def test_write_shims_never_overwrites_editor_shim(tmp_path: Path) -> None:
    """Hand-edited CLAUDE.md is preserved; the other 9 targets still written."""
    own = tmp_path / "CLAUDE.md"
    own.write_text("MY OWN INSTRUCTIONS\n", encoding="utf-8")
    result = write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    assert own in result.skipped
    assert own.read_text(encoding="utf-8") == "MY OWN INSTRUCTIONS\n"
    assert len(result.written) == 9


def test_write_shims_never_overwrites_skill(tmp_path: Path) -> None:
    """Hand-edited skill body is preserved; other skills + manifest still written."""
    own = tmp_path / ".claude" / "skills" / "codebase-debugging" / "SKILL.md"
    own.parent.mkdir(parents=True)
    own.write_text("MY OWN SKILL\n", encoding="utf-8")
    result = write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    assert own in result.skipped
    assert own.read_text(encoding="utf-8") == "MY OWN SKILL\n"
    # The other 4 skills should still be written.
    for name in _SKILL_NAMES:
        if name == "codebase-debugging":
            continue
        assert (tmp_path / ".claude" / "skills" / name / "SKILL.md").is_file()


def test_write_shims_never_overwrites_plugin_manifest(tmp_path: Path) -> None:
    own = tmp_path / ".claude-plugin" / "plugin.json"
    own.parent.mkdir(parents=True)
    own.write_text('{"name": "user-edited"}\n', encoding="utf-8")
    result = write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    assert own in result.skipped
    assert own.read_text(encoding="utf-8") == '{"name": "user-edited"}\n'


def test_refresh_rewrites_stale_deepdive_shim(tmp_path: Path) -> None:
    """DEC-091: a STALE Deepdive-generated shim (carries the fingerprint) is
    rewritten under refresh=True; the default still skips it."""
    brief = "docs/codebase/AGENT_BRIEF.md"
    claude = tmp_path / "CLAUDE.md"
    # Simulate a stale generated shim: our fingerprint, but old content.
    claude.write_text("# old\n_Generated by forensic-deepdive — stale five-tools shim._\n", "utf-8")
    # Without refresh: write-if-absent leaves the existing file (skipped).
    r1 = write_shims(tmp_path, brief)
    assert claude in r1.skipped and "stale five-tools" in claude.read_text(encoding="utf-8")
    # With refresh: the stale Deepdive shim is rewritten to current content.
    r2 = write_shims(tmp_path, brief, refresh=True)
    assert claude in r2.refreshed
    assert "stale five-tools" not in claude.read_text(encoding="utf-8")
    assert "forensic-deepdive" in claude.read_text(encoding="utf-8")


def test_refresh_never_touches_hand_edited_shim(tmp_path: Path) -> None:
    """DEC-091: refresh must NOT clobber a hand-edited file (no fingerprint)."""
    claude = tmp_path / "CLAUDE.md"
    claude.write_text("MY OWN INSTRUCTIONS — no fingerprint here\n", encoding="utf-8")
    result = write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md", refresh=True)
    assert claude in result.skipped
    assert claude.read_text(encoding="utf-8") == "MY OWN INSTRUCTIONS — no fingerprint here\n"


def test_refresh_is_noop_when_shim_already_current(tmp_path: Path) -> None:
    """An already-current generated shim is skipped (not needlessly rewritten)."""
    brief = "docs/codebase/AGENT_BRIEF.md"
    write_shims(tmp_path, brief)  # generate fresh
    r = write_shims(tmp_path, brief, refresh=True)  # nothing stale
    assert not r.refreshed
    assert (tmp_path / "CLAUDE.md") in r.skipped


# ---------------------------------------------------------------------------
# DEC-108: the five emitted skills carry no fingerprint, so DEC-091's gate could
# never refresh them. Found on a real 0.8 -> 0.9 upgrade (hermes-agent), where two
# stale skill bodies kept citing internal DEC ledger IDs that DEC-107 removed.
# ---------------------------------------------------------------------------

_SKILL_REL = Path(".claude") / "skills" / "codebase-impact-analysis" / "SKILL.md"

_STALE_SKILL = (
    "---\n"
    "name: codebase-impact-analysis\n"
    "description: Old one-line description from a previous release.\n"
    "---\n\n"
    "# Codebase impact analysis\n\n"
    "The graph tags every edge `EXTRACTED` / `INFERRED` / `AMBIGUOUS` (DEC-015).\n"
)


def test_refresh_rewrites_stale_emitted_skill_without_fingerprint(tmp_path: Path) -> None:
    """DEC-108: a skill written by <=0.9.0 has no `forensic-deepdive` fingerprint
    anywhere in its body, yet is ours by namespace and MUST refresh.

    This is the exact regression: before the fix `--refresh-shims` left the stale
    body in place, so an upgraded repo kept a dangling `DEC-015` reference.
    """
    brief = "docs/codebase/AGENT_BRIEF.md"
    skill = tmp_path / _SKILL_REL
    skill.parent.mkdir(parents=True)
    skill.write_text(_STALE_SKILL, encoding="utf-8")
    assert "forensic-deepdive" not in _STALE_SKILL  # the DEC-091 gate cannot see it

    r1 = write_shims(tmp_path, brief)  # write-if-absent leaves it
    assert skill in r1.skipped
    assert "DEC-015" in skill.read_text(encoding="utf-8")

    r2 = write_shims(tmp_path, brief, refresh=True)
    assert skill in r2.refreshed
    assert "DEC-015" not in skill.read_text(encoding="utf-8")


def test_refresh_never_touches_a_foreign_skill_in_our_directory(tmp_path: Path) -> None:
    """DEC-108: namespace ownership needs BOTH the path and the declared name.
    A user's own skill parked in one of our directories is left alone."""
    brief = "docs/codebase/AGENT_BRIEF.md"
    skill = tmp_path / _SKILL_REL
    skill.parent.mkdir(parents=True)
    foreign = "---\nname: my-own-skill\ndescription: Mine.\n---\n\n# Mine\n"
    skill.write_text(foreign, encoding="utf-8")

    r = write_shims(tmp_path, brief, refresh=True)
    assert skill in r.skipped
    assert skill.read_text(encoding="utf-8") == foreign


def test_refresh_never_touches_a_skill_outside_our_namespace(tmp_path: Path) -> None:
    """DEC-108: a `codebase-*`-shaped frontmatter outside `.claude/skills/` is
    not ours — the location has to agree too."""
    brief = "docs/codebase/AGENT_BRIEF.md"
    stray = tmp_path / "skills" / "codebase-impact-analysis" / "SKILL.md"
    stray.parent.mkdir(parents=True)
    stray.write_text(_STALE_SKILL, encoding="utf-8")

    write_shims(tmp_path, brief, refresh=True)
    assert stray.read_text(encoding="utf-8") == _STALE_SKILL


def test_no_internal_dec_ids_in_any_emitted_shim_or_skill(tmp_path: Path) -> None:
    """DEC-107/108: the artifact sweep in test_emit.py covered only the five
    markdown artifacts. Every file `write_shims` drops into a target repo is a
    consumer-facing surface too, and DECISIONS.md never ships — so none of the
    10 may cite an internal ledger ID either."""
    import re

    write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    leaks: dict[str, list[str]] = {}
    for path in sorted(tmp_path.rglob("*")):
        if not path.is_file():
            continue
        found = re.findall(r"DEC-\d+", path.read_text(encoding="utf-8", errors="ignore"))
        if found:
            leaks[str(path.relative_to(tmp_path))] = sorted(set(found))
    assert not leaks, f"emitted shims leak internal ledger IDs: {leaks}"


def test_cursor_shim_has_frontmatter(tmp_path: Path) -> None:
    write_shims(tmp_path, "x/AGENT_BRIEF.md")
    content = (tmp_path / ".cursor" / "rules" / "codebase.mdc").read_text(encoding="utf-8")
    assert content.startswith("---\n")
    assert "alwaysApply: true" in content


# ---------------------------------------------------------------------------
# Skill body invariants
# ---------------------------------------------------------------------------


def _read_skill(tmp_path: Path, name: str) -> str:
    return (tmp_path / ".claude" / "skills" / name / "SKILL.md").read_text(encoding="utf-8")


def _frontmatter_block(body: str) -> str:
    """Return the YAML frontmatter block (between the two ``---`` lines)."""
    assert body.startswith("---\n")
    end = body.index("\n---\n", 4)
    return body[4:end]


def _description_from_frontmatter(body: str) -> str:
    block = _frontmatter_block(body)
    for line in block.splitlines():
        if line.startswith("description:"):
            return line[len("description:") :].strip()
    raise AssertionError(f"description: missing from frontmatter\n{block}")


def test_every_skill_has_yaml_frontmatter_with_name_and_description(tmp_path: Path) -> None:
    write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    for name in _SKILL_NAMES:
        body = _read_skill(tmp_path, name)
        block = _frontmatter_block(body)
        assert f"name: {name}" in block, f"{name}: frontmatter missing name field"
        assert "description:" in block, f"{name}: frontmatter missing description"


def test_skill_descriptions_are_single_intent_and_bounded(tmp_path: Path) -> None:
    """DEC-002 / DEC-016 lesson: descriptions are the load-bearing selector.
    Each one must (a) name the user phrases that fire it ("Use when..."),
    (b) name what it should NOT fire on ("Do NOT use"), and (c) stay under
    a rough 200-token budget so the 5 descriptions together don't blow the
    skill-list metadata context."""
    write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    for name in _SKILL_NAMES:
        body = _read_skill(tmp_path, name)
        desc = _description_from_frontmatter(body)
        assert "Use when" in desc, f"{name}: description must say 'Use when'"
        assert "Do NOT use" in desc or "do NOT use" in desc, (
            f"{name}: description must say 'Do NOT use'"
        )
        # Roughly 1 token ≈ 4 chars for English text. 200 tokens ≈ 800 chars.
        # Keep a small headroom so we stay well inside the budget.
        assert len(desc) <= 900, (
            f"{name}: description {len(desc)} chars > 900 (≈225 tokens). "
            "Tighten it — DEC-016 cap is ~200 tokens."
        )


def test_skill_descriptions_are_distinct_intents(tmp_path: Path) -> None:
    """Each skill's description should mention a unique intent verb so the
    selector doesn't fire two skills on one user phrase. Spot-check anchors."""
    write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    intent_anchors = {
        "codebase-exploring": "walk me through",
        "codebase-debugging": "broken",
        "codebase-impact-analysis": "blast radius",
        "codebase-refactoring": "refactor",
        "codebase-onboarding": "joined",
    }
    for name, anchor in intent_anchors.items():
        desc = _description_from_frontmatter(_read_skill(tmp_path, name))
        assert anchor in desc, f"{name}: description missing anchor phrase {anchor!r}"


def test_skill_bodies_reference_agent_brief(tmp_path: Path) -> None:
    """Every skill must point readers at AGENT_BRIEF.md — the brief is the
    headline artifact (CLAUDE.md "Sacred abstractions")."""
    write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    for name in _SKILL_NAMES:
        body = _read_skill(tmp_path, name)
        assert "AGENT_BRIEF.md" in body, f"{name}: must mention AGENT_BRIEF.md"
        assert "docs/codebase/AGENT_BRIEF.md" in body, f"{name}: must use the configured brief path"


def test_skill_paths_respect_brief_location(tmp_path: Path) -> None:
    """The artifact directory in skill bodies should derive from brief_rel,
    not be hard-coded to ``docs/codebase``."""
    write_shims(tmp_path, "artifacts/AGENT_BRIEF.md")
    body = _read_skill(tmp_path, "codebase-exploring")
    assert "artifacts/MAP.md" in body
    assert "artifacts/AGENT_BRIEF.md" in body
    assert "docs/codebase" not in body


# ---------------------------------------------------------------------------
# Plugin manifest invariants
# ---------------------------------------------------------------------------


def test_plugin_manifest_is_valid_json(tmp_path: Path) -> None:
    write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    manifest = json.loads((tmp_path / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8"))
    assert manifest["name"] == "forensic-deepdive-codebase"
    assert "version" in manifest
    assert "description" in manifest


def test_plugin_manifest_lists_all_five_skills(tmp_path: Path) -> None:
    write_shims(tmp_path, "docs/codebase/AGENT_BRIEF.md")
    manifest = json.loads((tmp_path / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8"))
    listed = {s["name"] for s in manifest["skills"]}
    assert listed == set(_SKILL_NAMES)
    # Paths in the manifest should resolve to actual files on disk.
    for entry in manifest["skills"]:
        assert (tmp_path / entry["path"]).is_file()


def test_plugin_manifest_includes_repo_name(tmp_path: Path) -> None:
    """The manifest description names the target repo so a user with
    multiple analyzed repos can tell their plugins apart."""
    repo = tmp_path / "my-cool-repo"
    repo.mkdir()
    write_shims(repo, "docs/codebase/AGENT_BRIEF.md")
    manifest = json.loads((repo / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8"))
    assert "my-cool-repo" in manifest["description"]
