"""Release hygiene — the coupling `CLAUDE.md` asserts but nothing enforced (DEC-112).

`CLAUDE.md` says `examples/` and the findings docs are updated together, and the
verification checklist says every `AGENT_BRIEF.md` stays under the 5 KB cap. Both
were eyeball-enforced until now, and during the v0.9 pre-release that cost real
time: two of the eleven example directories were still carrying 0.8.0 footers and
24 stale ledger tokens each, and it was noticed halfway through the release rather
than on the first commit that bumped the version.

These assertions are cheap, and each one has already failed in the wild:

* footer version == `pyproject.toml` version — the two stale directories;
* no internal `DEC-NNN` ledger IDs — DEC-107/108, swept manually in v0.9 by a
  script that lived outside the repo;
* every brief within the 5 KB cap — the sacred limit from `CLAUDE.md`.

**When this fails during a release:** you bumped the version and have not
regenerated `examples/` yet. Run `scripts/regen_examples.py`. That is the intended
workflow — the red suite *is* the reminder, which is the whole point of the file.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).parent.parent
_EXAMPLES = _REPO_ROOT / "examples"

# The 5-artifact contract (CLAUDE.md "Sacred abstractions"). Names and count are
# part of the public API — a missing one here is a broken example, a renamed one
# is a broken contract.
_ARTIFACTS = (
    "MAP.md",
    "HOTPATHS.md",
    "ARCHAEOLOGY.md",
    "MENTAL_MODEL.md",
    "AGENT_BRIEF.md",
)

# AGENT_BRIEF.md hard cap: beyond this, instruction-following degrades (CLAUDE.md).
_BRIEF_CAP_BYTES = 5120

_FOOTER_VERSION = re.compile(r"Generated by forensic-deepdive (\d+\.\d+\.\d+)")


def _project_version() -> str:
    data = tomllib.loads((_REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    return str(data["project"]["version"])


def _example_dirs() -> list[Path]:
    return sorted(p for p in _EXAMPLES.iterdir() if p.is_dir())


def test_examples_directory_is_populated() -> None:
    """Vacuity guard: every assertion below iterates `examples/`, so an empty or
    missing directory would turn this whole module green while testing nothing."""
    assert _EXAMPLES.is_dir(), "examples/ is missing"
    assert len(_example_dirs()) >= 10, "examples/ should hold the full worked-example set"


@pytest.mark.parametrize("example", _example_dirs(), ids=lambda p: p.name)
def test_example_has_all_five_artifacts(example: Path) -> None:
    missing = [name for name in _ARTIFACTS if not (example / name).is_file()]
    assert not missing, f"{example.name}: missing {missing}"


@pytest.mark.parametrize("example", _example_dirs(), ids=lambda p: p.name)
def test_example_footers_match_the_project_version(example: Path) -> None:
    """The assertion that would have caught the two stale v0.9 directories on the
    commit that bumped the version, instead of by eye mid-release."""
    expected = _project_version()
    stale = {}
    for name in _ARTIFACTS:
        body = (example / name).read_text(encoding="utf-8")
        found = _FOOTER_VERSION.findall(body)
        assert found, f"{example.name}/{name}: no generated-by footer"
        if any(v != expected for v in found):
            stale[name] = sorted(set(found))
    assert not stale, (
        f"{example.name}: artifacts generated by an older release {stale} "
        f"(pyproject is {expected}). Regenerate with scripts/regen_examples.py."
    )


@pytest.mark.parametrize("example", _example_dirs(), ids=lambda p: p.name)
def test_example_brief_is_within_the_size_cap(example: Path) -> None:
    """CLAUDE.md's hard cap, enforced on every worked example rather than only on
    the fixture the verification step happens to run."""
    size = (example / "AGENT_BRIEF.md").stat().st_size
    assert size <= _BRIEF_CAP_BYTES, (
        f"{example.name}/AGENT_BRIEF.md is {size} b > {_BRIEF_CAP_BYTES} b cap. "
        "Overflow belongs in AGENT_BRIEF_DEEP.md."
    )


@pytest.mark.parametrize("example", _example_dirs(), ids=lambda p: p.name)
def test_example_cites_no_internal_ledger_ids(example: Path) -> None:
    """DEC-107/108: `DECISIONS.md` is gitignored and never ships, so a `DEC-NNN`
    in emitted output is a dangling reference for every reader.

    v0.9 swept for this with a script that lived outside the repo on one machine.
    This is that sweep, in the suite, where it runs on every commit.
    """
    leaks = {}
    for name in _ARTIFACTS:
        found = re.findall(r"DEC-\d+", (example / name).read_text(encoding="utf-8"))
        if found:
            leaks[name] = sorted(set(found))
    assert not leaks, f"{example.name}: emitted output cites internal ledger IDs: {leaks}"


def test_all_examples_share_one_version() -> None:
    """A mixed-version `examples/` means a partial regeneration was committed —
    exactly the v0.9 state. Reported once, with the split, rather than as N
    separate failures."""
    by_version: dict[str, list[str]] = {}
    for example in _example_dirs():
        for v in _FOOTER_VERSION.findall((example / "AGENT_BRIEF.md").read_text(encoding="utf-8")):
            by_version.setdefault(v, []).append(example.name)
    assert len(by_version) == 1, f"examples/ spans multiple releases: {by_version}"
