"""Editor / agent shims — point AI tools at the generated brief.

After ``extract`` writes the five artifacts, it drops thin shim files at the
repo root so Claude Code, Cursor, and Continue auto-discover AGENT_BRIEF.md.

Shims are written **only when the target does not already exist** — a
hand-written ``CLAUDE.md`` / ``AGENTS.md`` / editor rule is never overwritten.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ShimResult:
    """Which shim files were written and which were left alone."""

    written: list[Path] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)


def _plain_shim(brief_rel: str) -> str:
    return (
        "# Codebase brief for AI agents\n\n"
        f"This repository has a forensic deep-dive. **Read `{brief_rel}` "
        "first** — it is the headline brief for AI coding agents.\n\n"
        "Deeper detail lives alongside it: `MAP.md`, `HOTPATHS.md`, "
        "`ARCHAEOLOGY.md`, `MENTAL_MODEL.md`.\n\n"
        "_Generated by forensic-deepdive — regenerate with `forensic update`. "
        "Delete this file to opt out._\n"
    )


def _cursor_shim(brief_rel: str) -> str:
    return (
        "---\ndescription: Forensic codebase brief for AI agents\nalwaysApply: true\n---\n\n"
    ) + _plain_shim(brief_rel)


def write_shims(repo_path: Path, brief_rel_path: str) -> ShimResult:
    """Write editor/agent shims for *repo_path* pointing at *brief_rel_path*.

    *brief_rel_path* is the repo-relative posix path to AGENT_BRIEF.md.
    Existing targets are skipped, never overwritten.
    """
    repo_path = Path(repo_path)
    targets: dict[Path, str] = {
        repo_path / "CLAUDE.md": _plain_shim(brief_rel_path),
        repo_path / "AGENTS.md": _plain_shim(brief_rel_path),
        repo_path / ".cursor" / "rules" / "codebase.mdc": _cursor_shim(brief_rel_path),
        repo_path / ".continue" / "rules" / "codebase.md": _plain_shim(brief_rel_path),
    }
    result = ShimResult()
    for path, content in targets.items():
        if path.exists():
            result.skipped.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        result.written.append(path)
    return result
