"""Editor / agent shims — point AI tools at the generated brief.

After ``extract`` writes the five artifacts, it drops thin shim files at the
target repo root so Claude Code / Cursor / Continue / Codex auto-discover
the artifacts, and writes five single-intent Claude skills + a Claude Code
plugin manifest under ``.claude/`` so agents pick the right entry point
per task (DEC-031).

Every target is **write-if-absent** — a hand-edited shim, skill, or
manifest is never overwritten. To regenerate, delete the file (or the
``.claude/skills/codebase-*`` directory).

DEC-002's "three single-intent skills" rule governs the *internal* tooling
skills shipped with this project (``forensic-deepdive-extract`` etc.). The
five skills emitted into target repos here are a different concern: they
teach agents how to *consume* the artifacts, not how to invoke the CLI.
Each description follows the same load-bearing single-intent pattern.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

# ---------------------------------------------------------------------------
# Shim content
# ---------------------------------------------------------------------------

_PLUGIN_VERSION = "0.2.0"


def _plain_shim(brief_rel: str) -> str:
    return (
        "# Codebase brief for AI agents\n\n"
        f"This repository has a forensic deep-dive. **Read `{brief_rel}` "
        "first** — it is the headline brief for AI coding agents.\n\n"
        "Deeper detail lives alongside it: `MAP.md`, `HOTPATHS.md`, "
        "`ARCHAEOLOGY.md`, `MENTAL_MODEL.md`.\n\n"
        "Five single-intent skills under `.claude/skills/codebase-*/` "
        "tell Claude Code which artifact to consult for which question. "
        "An MCP server (`forensic serve`) exposes nine composite tools "
        "(`impact`, `context`, `archaeology`, `flow`, `query`, "
        "`record_insight`, `recall_insights`, `visualize`, `trace`) for agents "
        "that prefer programmatic queries.\n\n"
        "_Generated by forensic-deepdive — regenerate with `forensic update`. "
        "Delete this file to opt out._\n"
    )


def _cursor_shim(brief_rel: str) -> str:
    return (
        "---\ndescription: Forensic codebase brief for AI agents\nalwaysApply: true\n---\n\n"
    ) + _plain_shim(brief_rel)


# ---------------------------------------------------------------------------
# Claude Code plugin manifest (.claude-plugin/plugin.json)
# ---------------------------------------------------------------------------

_EMITTED_SKILL_NAMES = (
    "codebase-exploring",
    "codebase-debugging",
    "codebase-impact-analysis",
    "codebase-refactoring",
    "codebase-onboarding",
)


def _plugin_manifest(repo_name: str) -> str:
    payload = {
        "name": "forensic-deepdive-codebase",
        "version": _PLUGIN_VERSION,
        "description": (
            f"Forensic codebase brief for {repo_name} — five markdown artifacts "
            "(MAP, HOTPATHS, ARCHAEOLOGY, MENTAL_MODEL, AGENT_BRIEF) plus five "
            "single-intent Claude skills covering exploring / debugging / "
            "impact-analysis / refactoring / onboarding workflows."
        ),
        "author": {"name": "forensic-deepdive"},
        "keywords": ["codebase", "onboarding", "knowledge-graph", "code-review"],
        "skills": [
            {"name": name, "path": f".claude/skills/{name}/SKILL.md"}
            for name in _EMITTED_SKILL_NAMES
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


# ---------------------------------------------------------------------------
# Skill bodies — one per single-intent workflow
#
# Each skill is a markdown file with YAML frontmatter. The description in
# the frontmatter MUST be one line (YAML scalar) — built here via Python
# string concatenation so source-level lines stay under the 100-char lint
# cap while the rendered YAML scalar is a single long line, exactly as
# Anthropic's skill selector expects.
# ---------------------------------------------------------------------------


def _frontmatter(name: str, description: str) -> str:
    return f"---\nname: {name}\ndescription: {description}\n---\n\n"


def _skill_exploring(brief_rel: str, artifacts_dir: str) -> str:
    description = (
        "Orient quickly in this codebase. "
        'Use when the user says "walk me through this repo", '
        '"where do I start", "how is X organized", '
        '"explain the architecture", '
        "or opens an unfamiliar file and asks what it does. "
        f"Reads {artifacts_dir}/MENTAL_MODEL.md "
        f"(entry points, layers, domains) and {artifacts_dir}/MAP.md "
        "(most central files, key definitions). "
        "Do NOT use for bug-hunting (use codebase-debugging) "
        "or for predicting blast radius of a change "
        "(use codebase-impact-analysis)."
    )
    body = (
        "# Codebase exploring\n\n"
        "Read-only orientation. Answer 'what is this and how is it laid out' "
        "without re-deriving structure by walking files.\n\n"
        "## When to use\n"
        "- User is new to a region of code or the whole repo.\n"
        "- Question shape: 'what is this', 'how is X organized', "
        "'where does the request flow start', 'what are the main modules'.\n"
        "- User just opened an unfamiliar file and asks about it.\n\n"
        "## When NOT to use\n"
        "- User reports a bug or unexpected behavior → `codebase-debugging`.\n"
        "- User wants to change something and asks 'what will break' "
        "→ `codebase-impact-analysis`.\n"
        "- User is brand new to the team and wants the broad brief "
        "→ `codebase-onboarding`.\n"
        "- Question is code-semantic ('does this handle null') "
        "— just read the file.\n\n"
        "## How to answer\n\n"
        f"1. **Always read `{brief_rel}` first** — it's small and pins the "
        "never/always rules.\n"
        "2. Match the question shape:\n\n"
        "| Question shape | Artifact |\n"
        "|---|---|\n"
        f"| 'What are the entry points / domains' | `{artifacts_dir}/MENTAL_MODEL.md` |\n"
        f"| 'Most central / load-bearing files' | `{artifacts_dir}/MAP.md` |\n"
        f"| 'Key definitions in this module' | `{artifacts_dir}/MAP.md` (Key definitions) |\n"
        f"| 'What rules apply when editing X' | `{brief_rel}` |\n\n"
        "3. If an MCP server (`forensic serve`) is running, also call "
        "`context(symbol)` to get the symbol's neighborhood in one shot.\n\n"
        "## Citation rule\n"
        f"Cite `{artifacts_dir}/MAP.md:142-158` or `{brief_rel}:23`. "
        "Never paraphrase a fact without a line citation.\n"
    )
    return _frontmatter("codebase-exploring", description) + body


def _skill_debugging(brief_rel: str, artifacts_dir: str) -> str:
    description = (
        "Find the right place to look when something is broken. "
        "Use when the user reports an error, regression, crash, flaky test, "
        'or unexpected behavior and says "why is X broken", '
        '"trace this failure", "where does this exception come from", '
        '"what changed that could cause this". '
        f"Reads {artifacts_dir}/HOTPATHS.md "
        "(dependency hot spots, churn × centrality) "
        f"and {artifacts_dir}/ARCHAEOLOGY.md "
        "(recent commits, defect proximity). "
        "Do NOT use for greenfield design or pure orientation "
        "— use codebase-exploring."
    )
    body = (
        "# Codebase debugging\n\n"
        "Triangulate a bug to its likely region without re-reading the whole repo.\n\n"
        "## When to use\n"
        "- User reports an error / regression / flake / unexpected output.\n"
        "- Question shape: 'why is X broken', 'where does this exception "
        "originate', 'what changed that could cause this', "
        "'this used to work'.\n\n"
        "## When NOT to use\n"
        "- User is orienting / learning, not fixing → `codebase-exploring`.\n"
        "- User is planning a refactor → `codebase-refactoring`.\n"
        "- Question is about correctness of a single function → just read it.\n\n"
        "## How to answer\n\n"
        f"1. **Always read `{brief_rel}` first** — the never/always rules "
        "often pin the load-bearing call site.\n"
        "2. Match the question shape:\n\n"
        "| Question shape | Artifact |\n"
        "|---|---|\n"
        "| 'What are the hot spots / where is most activity' "
        f"| `{artifacts_dir}/HOTPATHS.md` (Dependency hot spots) |\n"
        "| 'What changed recently around X' "
        f"| `{artifacts_dir}/ARCHAEOLOGY.md` (Recent commits, churn) |\n"
        "| 'What's the defect-proximity neighborhood' "
        f"| `{artifacts_dir}/ARCHAEOLOGY.md` |\n"
        "| 'What co-changes with this file' "
        f"| `{artifacts_dir}/HOTPATHS.md` (Co-change clusters) |\n\n"
        "3. If `forensic serve` is running, call `archaeology(file_or_symbol)` "
        "for the full git-history view in one call — recent commits, dominant "
        "author, defect proximity, co-change cluster.\n\n"
        "## Citation rule\n"
        f"Cite `{artifacts_dir}/HOTPATHS.md:42` or "
        f"`{artifacts_dir}/ARCHAEOLOGY.md:78`. "
        "If a graph-mode HOTPATHS shows AMBIGUOUS-confidence edges around the "
        "suspect symbol, surface that — agents and humans both need to know "
        "the resolver wasn't sure.\n"
    )
    return _frontmatter("codebase-debugging", description) + body


def _skill_impact_analysis(brief_rel: str, artifacts_dir: str) -> str:
    description = (
        "Predict the blast radius before changing code. "
        'Use when the user proposes "rename X", "remove Y", '
        '"change the signature of Z", "deprecate this function", '
        '"what depends on this", "safe to delete". '
        "If MCP server is running, calls impact(symbol, direction='upstream') "
        "and context(symbol). "
        f"Otherwise reads {artifacts_dir}/HOTPATHS.md "
        f"(cross-file dependencies) and {brief_rel} (coupling rules). "
        "Do NOT use for orientation or pure debugging "
        "— use codebase-exploring or codebase-debugging."
    )
    body = (
        "# Codebase impact analysis\n\n"
        "Predict downstream effects of a change BEFORE making it. Never "
        "recommend a rename / removal / signature change without first "
        "surfacing callers and co-change neighbors.\n\n"
        "## When to use\n"
        "- User proposes a rename, signature change, removal, deprecation, "
        "or split.\n"
        "- Question shape: 'what depends on this', 'safe to delete X', "
        "'where is Y called from', 'what breaks if I change Z'.\n\n"
        "## When NOT to use\n"
        "- User is reading code to understand it → `codebase-exploring`.\n"
        "- User is hunting a bug → `codebase-debugging`.\n"
        "- User is restructuring with full knowledge of callers "
        "→ `codebase-refactoring`.\n\n"
        "## How to answer\n\n"
        f"1. **Always read `{brief_rel}` first** — coupling rules "
        "('if you touch X also touch Y') often pre-answer the question.\n"
        "2. **If MCP server is running** (`forensic serve`):\n"
        "   - `impact(symbol, depth=3, direction='upstream')` — every caller, "
        "depth-bucketed, with confidence per edge.\n"
        "   - `context(symbol)` — definition + callers + callees + parent + "
        "siblings + members + recent commits in one call.\n"
        "3. **If MCP isn't running:**\n\n"
        "| Question shape | Artifact |\n"
        "|---|---|\n"
        "| 'Cross-file dependencies' "
        f"| `{artifacts_dir}/HOTPATHS.md` (Cross-file dependencies) |\n"
        "| 'Coupling rules for this file' "
        f"| `{brief_rel}` (Always rules) |\n"
        "| 'Co-change cluster' "
        f"| `{artifacts_dir}/HOTPATHS.md` (Co-change clusters) |\n\n"
        "## Confidence discipline\n"
        "The graph tags every edge `EXTRACTED` / `INFERRED` / `AMBIGUOUS` "
        "(DEC-015). When recommending a change, **call out AMBIGUOUS callers "
        "explicitly** — the resolver was unsure, so the human should "
        "double-check.\n\n"
        "## Citation rule\n"
        f"Cite `{artifacts_dir}/HOTPATHS.md:42` or the MCP tool output "
        "verbatim. Never say 'X is safe to delete' without showing the "
        "caller list (even when empty — 'no callers found in "
        f"{artifacts_dir}/HOTPATHS.md and impact() returned 0 upstream').\n"
    )
    return _frontmatter("codebase-impact-analysis", description) + body


def _skill_refactoring(brief_rel: str, artifacts_dir: str) -> str:
    description = (
        "Run a refactor with awareness of coupling and co-change patterns. "
        'Use when the user says "refactor X", "extract method", '
        '"split this class", "consolidate duplicated logic", '
        '"move this to its own module". '
        f"Reads {brief_rel} coupling rules and "
        f"{artifacts_dir}/HOTPATHS.md co-change clusters; "
        "calls MCP context(symbol) and impact(symbol) when available. "
        "Do NOT use for single-file renames (just edit), "
        "bug-hunting (use codebase-debugging), "
        "or pure exploration (use codebase-exploring)."
    )
    body = (
        "# Codebase refactoring\n\n"
        "Coordinate multi-file structural changes against the codebase's "
        "coupling rules and co-change history. A refactor is not "
        "'rename + reformat' — it's 'move responsibility while preserving "
        "every caller's contract.'\n\n"
        "## When to use\n"
        "- User wants to extract / inline / split / consolidate code "
        "across files.\n"
        "- Question shape: 'refactor X to do Y', 'extract method', "
        "'split this class into A and B', 'consolidate this duplicated "
        "logic'.\n\n"
        "## When NOT to use\n"
        "- Change is contained in one file → just do the edit.\n"
        "- User is investigating a bug → `codebase-debugging`.\n"
        "- User is reading to understand → `codebase-exploring`.\n\n"
        "## How to answer\n\n"
        f"1. **Read `{brief_rel}` first.** The 'if you touch X also touch Y' "
        "rules pre-encode the co-change neighborhood — refactors that "
        "ignore them break things in adjacent files.\n"
        f"2. **Read `{artifacts_dir}/HOTPATHS.md` 'Co-change clusters' "
        "section.** Files that historically co-change with the target "
        "should be reviewed in the same PR.\n"
        "3. **If MCP server is running:**\n"
        "   - `context(target_symbol)` — full neighborhood "
        "(callers, callees, parent class, siblings, members, recent commits).\n"
        "   - `impact(target_symbol, direction='upstream')` — every caller "
        "that will need to compile after the change.\n"
        "4. **Surface the dominant author from ARCHAEOLOGY.md** if the target "
        "file has one — they own the historical context.\n\n"
        "## Pitfalls\n"
        "- Don't refactor a symbol with AMBIGUOUS callers without listing "
        "them first — the human should resolve the ambiguity.\n"
        "- Don't refactor a symbol whose co-change cluster includes files "
        "the user didn't mention — flag those files, ask if they should "
        "be in scope.\n"
        "- Don't auto-rename across a polyglot graph (DEC-012's "
        "language-scoped rule) without checking that the symbol's "
        "other-language references are intentional.\n\n"
        "## Citation rule\n"
        f"Cite every coupling rule (`{brief_rel}:23`) and every co-change "
        f"pair (`{artifacts_dir}/HOTPATHS.md:78`). "
        "Never propose a multi-file refactor without first showing the "
        "impact list.\n"
    )
    return _frontmatter("codebase-refactoring", description) + body


def _skill_onboarding(brief_rel: str, artifacts_dir: str) -> str:
    description = (
        "Brief a new engineer on this codebase. "
        'Use when the user says "I just joined this team", '
        '"onboard me to this repo", "I\'m new here — what should I know", '
        '"give me the first-day brief". '
        "Reads all five artifacts in order "
        f"({brief_rel} → MENTAL_MODEL → MAP → HOTPATHS → ARCHAEOLOGY) "
        "and surfaces ownership / bus-factor data from ARCHAEOLOGY. "
        "Do NOT use for specific bug-hunting (use codebase-debugging), "
        "targeted orientation (use codebase-exploring), "
        "or change-planning (use codebase-impact-analysis "
        "or codebase-refactoring)."
    )
    body = (
        "# Codebase onboarding\n\n"
        "The first-day brief. One pass through all five artifacts, ordered "
        "for a new engineer.\n\n"
        "## When to use\n"
        "- User explicitly signals they are new to this codebase / team.\n"
        "- Question shape: 'onboard me', 'what should I know', "
        "'give me the first-day brief', 'I'm new here'.\n\n"
        "## When NOT to use\n"
        "- User has a specific task (bug, feature, refactor) → use the "
        "targeted skill.\n"
        "- User is mid-task and asks a focused question → use "
        "`codebase-exploring` or `codebase-debugging`.\n\n"
        "## How to answer — read in this order\n\n"
        f"1. **`{brief_rel}` (≤ 5 KB)** — the never/always rules, the "
        "load-bearing symbol, the coupling rules. This is the floor; "
        "everything else is depth.\n"
        f"2. **`{artifacts_dir}/MENTAL_MODEL.md`** — entry points, layers, "
        "domains. The 'what is this product' answer.\n"
        f"3. **`{artifacts_dir}/MAP.md`** — most central files, key "
        "definitions. Where the weight is.\n"
        f"4. **`{artifacts_dir}/HOTPATHS.md`** — hot spots, cross-file "
        "dependencies, churn × centrality. What's actively changing.\n"
        f"5. **`{artifacts_dir}/ARCHAEOLOGY.md`** — top contributors with "
        "share %, bus factor, recent commits. "
        "**Who to ask about what.**\n\n"
        "## Surface ownership\n"
        "After the read-through, name the top 3 contributors by share % "
        "from ARCHAEOLOGY.md and what they own (most-touched files). "
        "Bus-factor warnings go up front. A new engineer needs to know "
        "whose code they're about to step on.\n\n"
        "## Citation rule\n"
        f"Cite every artifact line: `{brief_rel}:12`, "
        f"`{artifacts_dir}/ARCHAEOLOGY.md:34`. "
        "The brief should be navigable, not a paraphrase.\n\n"
        "## What to report back\n"
        "- One-paragraph 'what is this product' summary from MENTAL_MODEL.\n"
        "- 5 named load-bearing files with one-line descriptions from MAP.\n"
        "- Top 3 contributors with share % and the files they own from "
        "ARCHAEOLOGY.\n"
        f"- Every 'Always' rule from {brief_rel}, verbatim.\n"
        "- Suggested next-step skill: 'for a specific bug, switch to "
        "`codebase-debugging`; for a change, `codebase-impact-analysis`.'\n"
    )
    return _frontmatter("codebase-onboarding", description) + body


def _build_skills(brief_rel: str, artifacts_dir: str) -> dict[str, str]:
    return {
        "codebase-exploring": _skill_exploring(brief_rel, artifacts_dir),
        "codebase-debugging": _skill_debugging(brief_rel, artifacts_dir),
        "codebase-impact-analysis": _skill_impact_analysis(brief_rel, artifacts_dir),
        "codebase-refactoring": _skill_refactoring(brief_rel, artifacts_dir),
        "codebase-onboarding": _skill_onboarding(brief_rel, artifacts_dir),
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


@dataclass
class ShimResult:
    """Which shim / skill / manifest files were written and which were
    left alone (already existed)."""

    written: list[Path] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)


def _artifacts_dir_from_brief(brief_rel: str) -> str:
    """The artifacts dir is the parent of AGENT_BRIEF.md, posix-style.

    A path like ``docs/codebase/AGENT_BRIEF.md`` yields ``docs/codebase``.
    A bare ``AGENT_BRIEF.md`` yields ``.`` so the skill bodies still render
    a valid path.
    """
    parent = Path(brief_rel).parent.as_posix()
    return parent if parent and parent != "." else "."


def write_shims(repo_path: Path, brief_rel_path: str) -> ShimResult:
    """Write editor/agent shims, five emitted skills, and the Claude
    plugin manifest for *repo_path*, all pointing at *brief_rel_path*.

    *brief_rel_path* is the repo-relative posix path to AGENT_BRIEF.md.

    Every target is write-if-absent — existing files are skipped, never
    overwritten. The 4 editor shims preserve the v0.1 contract; the 5
    skills + plugin.json are the DEC-031 additions.
    """
    repo_path = Path(repo_path)
    artifacts_dir = _artifacts_dir_from_brief(brief_rel_path)
    repo_name = repo_path.name or "this repository"

    targets: dict[Path, str] = {
        # v0.1 editor shims.
        repo_path / "CLAUDE.md": _plain_shim(brief_rel_path),
        repo_path / "AGENTS.md": _plain_shim(brief_rel_path),
        repo_path / ".cursor" / "rules" / "codebase.mdc": _cursor_shim(brief_rel_path),
        repo_path / ".continue" / "rules" / "codebase.md": _plain_shim(brief_rel_path),
        # DEC-031: Claude Code plugin manifest.
        repo_path / ".claude-plugin" / "plugin.json": _plugin_manifest(repo_name),
    }
    # DEC-031: five emitted skills under .claude/skills/codebase-*/SKILL.md.
    for name, body in _build_skills(brief_rel_path, artifacts_dir).items():
        targets[repo_path / ".claude" / "skills" / name / "SKILL.md"] = body

    result = ShimResult()
    for path, content in targets.items():
        if path.exists():
            result.skipped.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        result.written.append(path)
    return result
